apiVersion: apps/v1
kind: Deployment
metadata:
  name: kv-store-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kv-store
  template:
    metadata:
      labels:
        app: kv-store
    spec:
      containers:
      - name: kv-store
        image: kv-store:latest
        ports:
        - containerPort: 50051
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        readinessProbe:
          httpGet:
            path: /health
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 10
